name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 5 1 * *'

jobs:
  build:
    name: ${{ matrix.arch }}
    runs-on: windows-2019
    # don't run pull requests from local branches twice
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      matrix:
        arch: [x86, x64]
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          # make Windows packages like Clang available in MSYS
          path-type: inherit
          # install MSYS packages
          install: make autoconf automake libtool pkg-config
      - name: Delete MinGW gmake
        # delete /c/Strawberry/c/bin/gmake built for MinGW that is found on runners, because we must use make built for MSYS
        run: if GMAKE_PATH=`which gmake`; then rm -f "$GMAKE_PATH"; fi
        shell: msys2 {0}
      - name: Install Windows packages
        run: choco install ninja
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - name: Build toolchain
        run: |
          :: use msys2.cmd from setup-msys2 as Bash shell, as it doesn't have msys2_shell.cmd used normally by build.bat
          set "BASH=msys2 -c"
          build.bat
        shell: cmd
      - name: Package release
        run: |
          tar -a -cf GNUstep-Windows-MSVC-${{matrix.arch}}.zip C:\GNUstep\${{matrix.arch}}
      - name: Update GitHub prerelease
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: GNUstep-Windows-MSVC-${{matrix.arch}}.zip
          tag: latest
          release_name: "Latest Build"
          prerelease: true
          overwrite: true
